language: android
android:
  components:
    - build-tools-23.0.3
    - android-23
    - android-L
    - sys-img-x86-android-tv-l
    - add-on
    - extra
script: ./gradlew clean assembleDebug crashlyticsUploadDistributionDebug